// @ts-ignore
const data = [
    {
        name: "Discipline",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/201.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_wordfortitude.jpg",
        talents: [
            [
                null,
                {
                    name: "Unbreakable Will",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_magic_magearmor.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to resist Stun, Fear, and Silence effects by an additional 3%.",
                        "Increases your chance to resist Stun, Fear, and Silence effects by an additional 6%.",
                        "Increases your chance to resist Stun, Fear, and Silence effects by an additional 9%.",
                        "Increases your chance to resist Stun, Fear, and Silence effects by an additional 12%.",
                        "Increases your chance to resist Stun, Fear, and Silence effects by an additional 15%.",
                    ]),
                },
                {
                    name: "Wand Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_wand_01.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your damage with Wands by 5%.",
                        "Increases your damage with Wands by 10%.",
                        "Increases your damage with Wands by 15%.",
                        "Increases your damage with Wands by 20%.",
                        "Increases your damage with Wands by 25%.",
                    ]),
                },
            ],
            [
                {
                    name: "Silent Resolve",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_manaregentotem.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the threat generated by your Holy and Discipline spells by 4% and reduces the chance your spells will be dispelled by 4%.",
                        "Reduces the threat generated by your Holy and Discipline spells by 8% and reduces the chance your spells will be dispelled by 8%.",
                        "Reduces the threat generated by your Holy and Discipline spells by 12% and reduces the chance your spells will be dispelled by 12%.",
                        "Reduces the threat generated by your Holy and Discipline spells by 16% and reduces the chance your spells will be dispelled by 16%.",
                        "Reduces the threat generated by your Holy and Discipline spells by 20% and reduces the chance your spells will be dispelled by 20%.",
                    ]),
                },
                {
                    name: "Improved Power Word: Fortitude",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_wordfortitude.jpg",
                    text: [
                        [
                            "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 15%, ",
                            createElement("span", { className: "changed" }, [
                                "and increases your total Stamina by 2%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by 30%, ",
                            createElement("span", { className: "changed" }, [
                                "and increases your total Stamina by 4%",
                            ]),
                            ".",
                        ],
                    ],
                },
                {
                    name: "Improved Power Word: Shield",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_powerwordshield.jpg",
                    text: [
                        [
                            "Increases the damage absorbed by your Power Word: Shield by 5%",
                            createElement("span", { className: "changed" }, [
                                ", reduces the cooldown by 2 sec, and reduces the mana cost by 5%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases the damage absorbed by your Power Word: Shield by 10%",
                            createElement("span", { className: "changed" }, [
                                ", reduces the cooldown by 3 sec, and reduces the mana cost by 10%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases the damage absorbed by your Power Word: Shield by 15%",
                            createElement("span", { className: "changed" }, [
                                ", reduces the cooldown by 4 sec, and reduces the mana cost by 15%",
                            ]),
                            ".",
                        ],
                    ],
                },
                {
                    name: "Martyrdom",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_tranquility.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 50% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 10%.",
                        "Gives you a 100% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike. The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by 20%.",
                    ]),
                },
            ],
            [
                {
                    name: "Absolution",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_absolution.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 5%.",
                        "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 10%.",
                        "Reduces the mana cost of your Dispel Magic, Cure Disease, Abolish Disease and Mass Dispel spells by 15%.",
                    ]),
                },
                {
                    name: "Inner Focus",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_frost_windwalkon.jpg",
                    text: formatUnchangedTalentTexts([
                        "When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.",
                    ]),
                },
                {
                    name: "Meditation",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_sleep.jpg",
                    text: [
                        [
                            "Allows ",
                            createElement("span", { className: "changed" }, ["17"]),
                            "% of your mana regeneration to continue while casting.",
                        ],
                        [
                            "Allows ",
                            createElement("span", { className: "changed" }, ["33"]),
                            "% of your mana regeneration to continue while casting.",
                        ],
                        [
                            "Allows ",
                            createElement("span", { className: "changed" }, ["50"]),
                            "% of your mana regeneration to continue while casting.",
                        ],
                    ],
                },
            ],
            [
                {
                    name: "Improved Inner Fire",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_innerfire.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the armor bonus of your Inner Fire spell by 10%.",
                        "Increases the armor bonus of your Inner Fire spell by 20%.",
                        "Increases the armor bonus of your Inner Fire spell by 30%.",
                    ]),
                },
                {
                    name: "Mental Agility",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_hibernation.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the mana cost of your instant cast spells by 2%.",
                        "Reduces the mana cost of your instant cast spells by 4%.",
                        "Reduces the mana cost of your instant cast spells by 6%.",
                        "Reduces the mana cost of your instant cast spells by 8%.",
                        "Reduces the mana cost of your instant cast spells by 10%.",
                    ]),
                },
                null,
                {
                    name: "Improved Mana Burn",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_manaburn.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the casting time of your Mana Burn spell by 0.5 sec.",
                        "Reduces the casting time of your Mana Burn spell by 1 sec.",
                    ]),
                },
            ],
            [
                null,
                {
                    name: "Mental Strength",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_enchantarmor.jpg",
                    text: [
                        [
                            "Increases your ",
                            createElement("span", { className: "changed" }, [
                                "total Intellect by 3%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases your ",
                            createElement("span", { className: "changed" }, [
                                "total Intellect by 6%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases your ",
                            createElement("span", { className: "changed" }, [
                                "total Intellect by 9%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases your ",
                            createElement("span", { className: "changed" }, [
                                "total Intellect by 12%",
                            ]),
                            ".",
                        ],
                        [
                            "Increases your ",
                            createElement("span", { className: "changed" }, [
                                "total Intellect by 15%",
                            ]),
                            ".",
                        ],
                    ],
                },
                {
                    name: "Divine Spirit",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_divinespirit.jpg",
                    text: formatUnchangedTalentTexts([
                        "Holy power infuses the target, increasing their Spirit by 17 for 30 min.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Improved Divine Spirit",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_divinespirit.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your Divine Spirit and Prayer of Spirit spells also increase the target's spell damage and healing by an amount equal to 5% of their total Spirit.",
                        "Your Divine Spirit and Prayer of Spirit spells also increase the target's spell damage and healing by an amount equal to 10% of their total Spirit.",
                    ]),
                    req: "left",
                    reqDist: 1,
                },
            ],
            [
                {
                    name: "Focused Power",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_focusedpower.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your Smite, Mind Blast and Mass Dispel spells have an additional 2% chance to hit.  In addition, your Mass Dispel cast time is reduced by 0.5 sec.",
                        "Your Smite, Mind Blast and Mass Dispel spells have an additional 4% chance to hit.  In addition, your Mass Dispel cast time is reduced by 1 sec.",
                    ]),
                },
                null,
                {
                    name: "Force of Will",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_slowingtotem.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 1%.",
                        "Increases your spell damage by 2% and the critical strike chance of your offensive spells by 2%.",
                        "Increases your spell damage by 3% and the critical strike chance of your offensive spells by 3%.",
                        "Increases your spell damage by 4% and the critical strike chance of your offensive spells by 4%.",
                        "Increases your spell damage by 5% and the critical strike chance of your offensive spells by 5%.",
                    ]),
                },
            ],
            [
                {
                    name: "Focused Will",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_arcane_focusedpower.jpg",
                    text: [
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases your spell critical effect chance by 1%, and",
                            ]),
                            " after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 2% and increasing healing effects on you by 4%.  Stacks up to 3 times.  Lasts 8 sec.",
                        ],
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases your spell critical effect chance by 2%, and",
                            ]),
                            " after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 3% and increasing healing effects on you by 7%.  Stacks up to 3 times.  Lasts 8 sec.",
                        ],
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases your spell critical effect chance by 3%, and",
                            ]),
                            " after taking a critical hit you gain the Focused Will effect, reducing all damage taken by 4% and increasing healing effects on you by 10%.  Stacks up to 3 times.  Lasts 8 sec.",
                        ],
                    ],
                },
                {
                    name: "Power Infusion",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_powerinfusion.jpg",
                    text: formatUnchangedTalentTexts([
                        "Infuses the target with power, increasing spell casting speed by 20% and reducing the mana cost of all spells by 20%.  Lasts 15 sec.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Reflective Shield",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_powerwordshield.jpg",
                    text: formatUnchangedTalentTexts([
                        "Causes 10% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
                        "Causes 20% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
                        "Causes 30% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
                        "Causes 40% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
                        "Causes 50% of the damage absorbed by your Power Word: Shield to reflect back at the attacker.  This damage causes no threat.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Enlightenment",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_arcane_mindmastery.jpg",
                    text: [
                        [
                            "Increases Spirit ",
                            createElement("span", { className: "changed" }, [
                                "and Spell Haste",
                            ]),
                            " by 1%.",
                        ],
                        [
                            "Increases Spirit ",
                            createElement("span", { className: "changed" }, [
                                "and Spell Haste",
                            ]),
                            " by 2%.",
                        ],
                        [
                            "Increases Spirit ",
                            createElement("span", { className: "changed" }, [
                                "and Spell Haste",
                            ]),
                            " by 3%.",
                        ],
                        [
                            "Increases Spirit ",
                            createElement("span", { className: "changed" }, [
                                "and Spell Haste",
                            ]),
                            " by 4%.",
                        ],
                        [
                            "Increases Spirit ",
                            createElement("span", { className: "changed" }, [
                                "and Spell Haste",
                            ]),
                            " by 5%.",
                        ],
                    ],
                },
                null,
                null,
            ],
            [
                null,
                {
                    name: "Pain Suppression",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_painsupression.jpg",
                    text: formatUnchangedTalentTexts([
                        "Instantly reduces a friendly target's threat by 5%, reduces all damage taken by 40% and increases resistance to Dispel mechanics by 65% for 8 sec.",
                    ]),
                },
                null,
                null,
            ],
        ],
    },
    {
        name: "Holy",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/202.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_guardianspirit.jpg",
        talents: [
            [
                {
                    name: "Healing Focus",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_healingfocus.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 35% chance to avoid interruption caused by damage while casting any healing spell.",
                        "Gives you a 70% chance to avoid interruption caused by damage while casting any healing spell.",
                    ]),
                },
                {
                    name: "Improved Renew",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_renew.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the amount healed by your Renew spell by 5%.",
                        "Increases the amount healed by your Renew spell by 10%.",
                        "Increases the amount healed by your Renew spell by 15%.",
                    ]),
                },
                {
                    name: "Holy Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_sealofsalvation.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the critical effect chance of your Holy spells by 1%.",
                        "Increases the critical effect chance of your Holy spells by 2%.",
                        "Increases the critical effect chance of your Holy spells by 3%.",
                        "Increases the critical effect chance of your Holy spells by 4%.",
                        "Increases the critical effect chance of your Holy spells by 5%.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Spell Warding",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_spellwarding.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces all spell damage taken by 2%.",
                        "Reduces all spell damage taken by 4%.",
                        "Reduces all spell damage taken by 6%.",
                        "Reduces all spell damage taken by 8%.",
                        "Reduces all spell damage taken by 10%.",
                    ]),
                },
                {
                    name: "Divine Fury",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_sealofwrath.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1 sec.",
                        "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2 sec.",
                        "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3 sec.",
                        "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4 sec.",
                        "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5 sec.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Holy Nova",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_holynova.jpg",
                    text: formatUnchangedTalentTexts([
                        "Causes an explosion of holy light around the caster, causing 28 to 33 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 52 to 61.  These effects cause no threat.",
                    ]),
                },
                {
                    name: "Blessed Recovery",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_blessedrecovery.jpg",
                    text: formatUnchangedTalentTexts([
                        "After being struck by a melee or ranged critical hit, heal 8% of the damage taken over 6 sec.",
                        "After being struck by a melee or ranged critical hit, heal 16% of the damage taken over 6 sec.",
                        "After being struck by a melee or ranged critical hit, heal 25% of the damage taken over 6 sec.",
                    ]),
                },
                null,
                {
                    name: "Inspiration",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_layonhands.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your target's armor by 8% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Prayer of Healing, or Circle of Healing spell.",
                        "Increases your target's armor by 16% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Prayer of Healing, or Circle of Healing spell.",
                        "Increases your target's armor by 25% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, Binding Heal, Prayer of Healing, or Circle of Healing spell.",
                    ]),
                },
            ],
            [
                {
                    name: "Holy Reach",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_purify.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova and Circle of Healing spells by 10%.",
                        "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing, Holy Nova and Circle of Healing spells by 20%.",
                    ]),
                },
                {
                    name: "Improved Healing",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_heal02.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 5%.",
                        "Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 10%.",
                        "Reduces the mana cost of your Lesser Heal, Heal, and Greater Heal spells by 15%.",
                    ]),
                },
                {
                    name: "Searing Light",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_searinglightpriest.jpg",
                    text: [
                        [
                            "Increases the damage of your Smite and Holy Fire, ",
                            createElement("span", { className: "changed" }, [
                                "and Holy Nova",
                            ]),
                            " spells by 5%.",
                        ],
                        [
                            "Increases the damage of your Smite and Holy Fire, ",
                            createElement("span", { className: "changed" }, [
                                "and Holy Nova",
                            ]),
                            " spells by 10%.",
                        ],
                    ],
                    req: "up",
                    reqDist: 2,
                },
                null,
            ],
            [
                {
                    name: "Healing Prayers",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_prayerofhealing02.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by 10%.",
                        "Reduces the mana cost of your Prayer of Healing and Prayer of Mending spell by 20%.",
                    ]),
                },
                {
                    name: "Spirit of Redemption",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_enchant_essenceeternallarge.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases total Spirit by 5% and upon death, the priest becomes the Spirit of Redemption for 15 sec.  The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects.  While in this form the priest can cast any healing spell free of cost.  When the effect ends, the priest dies.",
                    ]),
                },
                {
                    name: "Spiritual Guidance",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_spiritualguidence.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases spell damage and healing by up to 5% of your total Spirit.",
                        "Increases spell damage and healing by up to 10% of your total Spirit.",
                        "Increases spell damage and healing by up to 15% of your total Spirit.",
                        "Increases spell damage and healing by up to 20% of your total Spirit.",
                        "Increases spell damage and healing by up to 25% of your total Spirit.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Surge of Light",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_surgeoflight.jpg",
                    text: [
                        [
                            "Your spell criticals have a 25% chance to cause your next Smite spell to be instant cast and cost no mana",
                            createElement("span", { className: "changed" }, ["."]),
                            "  This effect lasts 10 sec.",
                        ],
                        [
                            "Your spell criticals have a 50% chance to cause your next Smite spell to be instant cast and cost no mana",
                            createElement("span", { className: "changed" }, ["."]),
                            "  This effect lasts 10 sec.",
                        ],
                    ],
                },
                null,
                {
                    name: "Spiritual Healing",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_moonglow.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the amount healed by your healing spells by 2%.",
                        "Increases the amount healed by your healing spells by 4%.",
                        "Increases the amount healed by your healing spells by 6%.",
                        "Increases the amount healed by your healing spells by 8%.",
                        "Increases the amount healed by your healing spells by 10%.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Holy Concentration",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_fanaticism.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 2% chance to enter a Clearcasting state after casting any Flash Heal, Binding Heal, or Greater Heal spell.  The Clearcasting state reduces the mana cost of your next Flash Heal, Binding Heal, or Greater Heal spell by 100%.",
                        "Gives you a 4% chance to enter a Clearcasting state after casting any Flash Heal, Binding Heal, or Greater Heal spell.  The Clearcasting state reduces the mana cost of your next Flash Heal, Binding Heal, or Greater Heal spell by 100%.",
                        "Gives you a 6% chance to enter a Clearcasting state after casting any Flash Heal, Binding Heal, or Greater Heal spell.  The Clearcasting state reduces the mana cost of your next Flash Heal, Binding Heal, or Greater Heal spell by 100%.",
                    ]),
                },
                {
                    name: "Lightwell",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_summonlightwell.jpg",
                    text: formatUnchangedTalentTexts([
                        "Creates a Holy Lightwell.  Members of your raid or party can click the Lightwell to restore 801 health over 6 sec.  Any damage taken will cancel the effect.  Lightwell lasts for 3 min or 5 charges.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Blessed Resilience",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_blessedresillience.jpg",
                    text: [
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases the effectiveness of healing spells by 1%",
                            ]),
                            ", and critical hits made against you have a 20% chance to prevent you from being critically hit again for 6 sec.",
                        ],
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases the effectiveness of healing spells by 2%",
                            ]),
                            ", and critical hits made against you have a 40% chance to prevent you from being critically hit again for 6 sec.",
                        ],
                        [
                            createElement("span", { className: "changed" }, [
                                "Increases the effectiveness of healing spells by 3%",
                            ]),
                            ", and critical hits made against you have a 60% chance to prevent you from being critically hit again for 6 sec.",
                        ],
                    ],
                },
                null,
            ],
            [
                null,
                {
                    name: "Empowered Healing",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_greaterheal.jpg",
                    text: [
                        [
                            "Your Greater Heal spell gains an additional 4% and your Flash Heal and Binding Heal gain an additional 2% of your bonus healing effects.",
                            createElement("span", { className: "changed" }, [
                                " Your Smite spell gains additional spell damage equal to 5% of your healing power.",
                            ]),
                        ],
                        [
                            "Your Greater Heal spell gains an additional 8% and your Flash Heal and Binding Heal gain an additional 4% of your bonus healing effects.",
                            createElement("span", { className: "changed" }, [
                                " Your Smite spell gains additional spell damage equal to 10% of your healing power.",
                            ]),
                        ],
                        [
                            "Your Greater Heal spell gains an additional 12% and your Flash Heal and Binding Heal gain an additional 6% of your bonus healing effects.",
                            createElement("span", { className: "changed" }, [
                                " Your Smite spell gains additional spell damage equal to 15% of your healing power.",
                            ]),
                        ],
                        [
                            "Your Greater Heal spell gains an additional 16% and your Flash Heal and Binding Heal gain an additional 8% of your bonus healing effects.",
                            createElement("span", { className: "changed" }, [
                                " Your Smite spell gains additional spell damage equal to 20% of your healing power.",
                            ]),
                        ],
                        [
                            "Your Greater Heal spell gains an additional 20% and your Flash Heal and Binding Heal gain an additional 10% of your bonus healing effects.",
                            createElement("span", { className: "changed" }, [
                                " Your Smite spell gains additional spell damage equal to 25% of your healing power.",
                            ]),
                        ],
                    ],
                },
                null,
                null,
            ],
            [
                null,
                {
                    name: "Circle of Healing",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_circleofrenewal.jpg",
                    text: formatUnchangedTalentTexts([
                        "Heals friendly target and that target's party members within 15 yards of the target for 246 to 271.",
                    ]),
                },
                null,
                null,
            ],
        ],
    },
    {
        name: "Shadow",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/203.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowwordpain.jpg",
        talents: [
            [
                null,
                {
                    name: "Spirit Tap",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_requiem.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                        "Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                        "Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                        "Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                        "Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor.  For the duration, your mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                    ]),
                },
                {
                    name: "Blackout",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_gathershadows.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives your Shadow damage spells a 2% chance to stun the target for 3 sec.",
                        "Gives your Shadow damage spells a 4% chance to stun the target for 3 sec.",
                        "Gives your Shadow damage spells a 6% chance to stun the target for 3 sec.",
                        "Gives your Shadow damage spells a 8% chance to stun the target for 3 sec.",
                        "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Shadow Affinity",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowward.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the threat generated by your Shadow spells by 8%.",
                        "Reduces the threat generated by your Shadow spells by 16%.",
                        "Reduces the threat generated by your Shadow spells by 25%.",
                    ]),
                },
                {
                    name: "Improved Shadow Word: Pain",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowwordpain.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the duration of your Shadow Word: Pain spell by 3 sec.",
                        "Increases the duration of your Shadow Word: Pain spell by 6 sec.",
                    ]),
                },
                {
                    name: "Shadow Focus",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_burningspirit.jpg",
                    text: [
                        [
                            "Reduces your target's chance to resist your Shadow spells by 2% ",
                            createElement("span", { className: "changed" }, [
                                "and reduces the mana cost of your Shadow spells by 1%.",
                            ]),
                        ],
                        [
                            "Reduces your target's chance to resist your Shadow spells by 4%.",
                            createElement("span", { className: "changed" }, [
                                "and reduces the mana cost of your Shadow spells by 2%.",
                            ]),
                        ],
                        [
                            "Reduces your target's chance to resist your Shadow spells by 6%.",
                            createElement("span", { className: "changed" }, [
                                "and reduces the mana cost of your Shadow spells by 3%.",
                            ]),
                        ],
                        [
                            "Reduces your target's chance to resist your Shadow spells by 8%.",
                            createElement("span", { className: "changed" }, [
                                "and reduces the mana cost of your Shadow spells by 4%.",
                            ]),
                        ],
                        [
                            "Reduces your target's chance to resist your Shadow spells by 10%.",
                            createElement("span", { className: "changed" }, [
                                "and reduces the mana cost of your Shadow spells by 5%.",
                            ]),
                        ],
                    ],
                },
                null,
            ],
            [
                {
                    name: "Improved Psychic Scream",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_psychicscream.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Psychic Scream spell by 2 sec.",
                        "Reduces the cooldown of your Psychic Scream spell by 4 sec.",
                    ]),
                },
                {
                    name: "Improved Mind Blast",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_unholyfrenzy.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Mind Blast spell by 0.5 sec.",
                        "Reduces the cooldown of your Mind Blast spell by 1 sec.",
                        "Reduces the cooldown of your Mind Blast spell by 1.5 sec.",
                        "Reduces the cooldown of your Mind Blast spell by 2 sec.",
                        "Reduces the cooldown of your Mind Blast spell by 2.5 sec.",
                    ]),
                },
                {
                    name: "Mind Flay",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_siphonmana.jpg",
                    text: formatUnchangedTalentTexts([
                        "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Veiled Shadows (old Improved Fade)",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_magic_lesserinvisibilty.jpg",
                    text: [
                        [
                            "Decreases the cooldown of your Fade ability by 3 sec. ",
                            createElement("span", { className: "changed" }, [
                                "and reduces the cooldown of your Shadowfiend ability by 1 minute.",
                            ]),
                        ],
                        [
                            "Decreases the cooldown of your Fade ability by 6 sec. ",
                            createElement("span", { className: "changed" }, [
                                "and reduces the cooldown of your Shadowfiend ability by 2 minutes.",
                            ]),
                        ],
                    ],
                },
                {
                    name: "Shadow Reach",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_chilltouch.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the range of your offensive Shadow spells by 10%.",
                        "Increases the range of your offensive Shadow spells by 20%.",
                    ]),
                },
                {
                    name: "Shadow Weaving",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_blackplague.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your Shadow damage spells have a 20% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec.  Stacks up to 5 times.",
                        "Your Shadow damage spells have a 40% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec.  Stacks up to 5 times.",
                        "Your Shadow damage spells have a 60% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec.  Stacks up to 5 times.",
                        "Your Shadow damage spells have a 80% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec.  Stacks up to 5 times.",
                        "Your Shadow damage spells have a 100% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 2% and lasts 15 sec.  Stacks up to 5 times.",
                    ]),
                },
            ],
            [
                {
                    name: "Silence",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_impphaseshift.jpg",
                    text: formatUnchangedTalentTexts([
                        "Silences the target, preventing them from casting spells for 5 sec.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Vampiric Embrace",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_unsummonbuilding.jpg",
                    text: formatUnchangedTalentTexts([
                        "Afflicts your target with Shadow energy that causes all party members to be healed for 15% of any Shadow spell damage you deal for 1 min.",
                    ]),
                },
                {
                    name: "Improved Vampiric Embrace",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_improvedvampiricembrace.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the percentage healed by Vampiric Embrace by an additional 5%.",
                        "Increases the percentage healed by Vampiric Embrace by an additional 10%.",
                    ]),
                    req: "left",
                    reqDist: 1,
                },
                {
                    name: "Focused Mind",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_focusedmind.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 5%.",
                        "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 10%.",
                        "Reduces the mana cost of your Mind Blast, Mind Control and Mind Flay spells by 15%.",
                    ]),
                },
            ],
            [
                {
                    name: "Shadow Resilience",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_grimward.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the chance you'll be critically hit by all spells by 2%.",
                        "Reduces the chance you'll be critically hit by all spells by 4%.",
                    ]),
                },
                null,
                {
                    name: "Darkness",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_twilight.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your Shadow spell damage by 2%.",
                        "Increases your Shadow spell damage by 4%.",
                        "Increases your Shadow spell damage by 6%.",
                        "Increases your Shadow spell damage by 8%.",
                        "Increases your Shadow spell damage by 10%.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Shadowform",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowform.jpg",
                    text: formatUnchangedTalentTexts([
                        "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%.  However, you may not cast Holy spells while in this form.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Shadow Power",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_shadowpower.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 3%.",
                        "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 6%.",
                        "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 9%.",
                        "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 12%.",
                        "Increases the critical strike chance of your Mind Blast and Shadow Word: Death spells by 15%.",
                    ]),
                },
                null,
            ],
            [
                null,
                null,
                {
                    name: "Misery",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_misery.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional 1% spell damage.",
                        "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional 2% spell damage.",
                        "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional 3% spell damage.",
                        "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional 4% spell damage.",
                        "Your Shadow Word: Pain, Mind Flay and Vampiric Touch spells also cause the target to take an additional 5% spell damage.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Vampiric Touch",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_stoicism.jpg",
                    text: formatUnchangedTalentTexts([
                        "Causes 450 Shadow damage over 15 sec to your target and causes all party members to gain mana equal to 5% of any Shadow spell damage you deal.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                null,
                null,
            ],
        ],
    },
];
// @ts-ignore
const otherchanges = [];
