// @ts-ignore
const data = [
    {
        name: "Arms",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/161.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_eviscerate.jpg",
        talents: [
            [
                {
                    name: "Improved Heroic Strike",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_ambush.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cost of your Heroic Strike ability by 1 rage point.",
                        "Reduces the cost of your Heroic Strike ability by 2 rage points.",
                        "Reduces the cost of your Heroic Strike ability by 3 rage points.",
                    ]),
                },
                {
                    name: "Deflection",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_parry.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your Parry chance by 1%.",
                        "Increases your Parry chance by 2%.",
                        "Increases your Parry chance by 3%.",
                        "Increases your Parry chance by 4%.",
                        "Increases your Parry chance by 5%.",
                    ]),
                },
                {
                    name: "Improved Rend",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_gouge.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the bleed damage done by your Rend ability by 25%.",
                        "Increases the bleed damage done by your Rend ability by 50%.",
                        "Increases the bleed damage done by your Rend ability by 75%.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Charge",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_charge.jpg",
                    text: [
                        [
                            "Increases the amount of rage generated by your Charge ability by ",
                            change("5", "3"),
                            ".",
                        ],
                        [
                            "Increases the amount of rage generated by your Charge ability by ",
                            change("10", "6"),
                            ".",
                        ],
                    ],
                },
                {
                    name: "Iron Will",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_magic_magearmor.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to resist Stun and Charm effects by an additional 3%.",
                        "Increases your chance to resist Stun and Charm effects by an additional 6%.",
                        "Increases your chance to resist Stun and Charm effects by an additional 9%.",
                        "Increases your chance to resist Stun and Charm effects by an additional 12%.",
                        "Increases your chance to resist Stun and Charm effects by an additional 15%.",
                    ]),
                },
                {
                    name: "Improved Thunder Clap",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_thunderclap.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cost of your Thunder Clap ability by 1 rage point and increases the damage by 40% and the slowing effect by an additional 4%.",
                        "Reduces the cost of your Thunder Clap ability by 2 rage points and increases the damage by 70% and the slowing effect by an additional 7%.",
                        "Reduces the cost of your Thunder Clap ability by 4 rage points and increases the damage by 100% and the slowing effect by an additional 10%.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Overpower",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_sword_05.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the critical strike chance of your Overpower ability by 25%.",
                        "Increases the critical strike chance of your Overpower ability by 50%.",
                    ]),
                },
                {
                    name: "Anger Management",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_blessingofstamina.jpg",
                    text: formatUnchangedTalentTexts([
                        "Generates 1 rage per 3 seconds while in combat.",
                    ]),
                },
                {
                    name: "Deep Wounds",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_backstab.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
                        "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
                        "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Two-Handed Weapon Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_axe_09.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the damage you deal with two-handed melee weapons by 1%.",
                        "Increases the damage you deal with two-handed melee weapons by 2%.",
                        "Increases the damage you deal with two-handed melee weapons by 3%.",
                        "Increases the damage you deal with two-handed melee weapons by 4%.",
                        "Increases the damage you deal with two-handed melee weapons by 5%.",
                    ]),
                },
                {
                    name: "Impale",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_searingarrow.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
                        "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%.",
                    ]),
                    req: "up",
                    reqDist: 1,
                },
                null,
            ],
            [
                {
                    name: "Poleaxe Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_axe_06.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to get a critical strike with Axes and Polearms by 1%.",
                        "Increases your chance to get a critical strike with Axes and Polearms by 2%.",
                        "Increases your chance to get a critical strike with Axes and Polearms by 3%.",
                        "Increases your chance to get a critical strike with Axes and Polearms by 4%.",
                        "Increases your chance to get a critical strike with Axes and Polearms by 5%.",
                    ]),
                },
                {
                    name: "Death Wish",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_deathpact.jpg",
                    text: formatUnchangedTalentTexts([
                        "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but increases all damage taken by 5%.  Lasts 30 sec.",
                    ]),
                },
                {
                    name: "Mace Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_mace_01.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace.",
                        "Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace.  More effective than Mace Specialization (Rank 1).",
                        "Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace.  More effective than Mace Specialization (Rank 2).",
                        "Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace.  More effective than Mace Specialization (Rank 3).",
                        "Gives your melee attacks a chance to stun your target for 3 sec and generate 7 rage when using a Mace.  More effective than Mace Specialization (Rank 4).",
                    ]),
                },
                {
                    name: "Sword Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_sword_27.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 1% chance to get an extra attack on the same target after hitting your target with your Sword.",
                        "Gives you a 2% chance to get an extra attack on the same target after hitting your target with your Sword.",
                        "Gives you a 3% chance to get an extra attack on the same target after hitting your target with your Sword.",
                        "Gives you a 4% chance to get an extra attack on the same target after hitting your target with your Sword.",
                        "Gives you a 5% chance to get an extra attack on the same target after hitting your target with your Sword.",
                    ]),
                },
            ],
            [
                {
                    name: "Improved Intercept",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_sprint.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Intercept ability by 5 sec.",
                        "Reduces the cooldown of your Intercept ability by 10 sec.",
                    ]),
                },
                null,
                {
                    name: "Improved Hamstring",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_shockwave.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.",
                        "Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec.",
                        "Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec.",
                    ]),
                },
                {
                    name: "Improved Disciplines",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_improveddisciplines.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min and increases their duration by 2 sec.",
                        "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 7 min and increases their duration by 4 sec.",
                        "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 10 min and increases their duration by 6 sec.",
                    ]),
                },
            ],
            [
                {
                    name: "Blood Frenzy",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_bloodfrenzy.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%.",
                        "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%.",
                    ]),
                },
                {
                    name: "Mortal Strike",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_savageblow.jpg",
                    text: formatUnchangedTalentTexts([
                        "A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Second Wind",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_hunter_harass.jpg",
                    text: formatUnchangedTalentTexts([
                        "Whenever you are struck by a Stun or Immobilize effect you will generate 10 rage and 5% of your total health over 10 sec.",
                        "Whenever you are struck by a Stun or Immobilize effect you will generate 20 rage and 10% of your total health over 10 sec.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Improved Mortal Strike",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_savageblow.jpg",
                    text: [
                        [
                            "Reduces the cooldown of your Mortal Strike ability by 0.2 sec and increases its damage by ",
                            change("2", "1"),
                            "%.",
                        ],
                        [
                            "Reduces the cooldown of your Mortal Strike ability by 0.4 sec and increases its damage by ",
                            change("4", "2"),
                            "%.",
                        ],
                        [
                            "Reduces the cooldown of your Mortal Strike ability by 0.6 sec and increases its damage by ",
                            change("6", "3"),
                            "%.",
                        ],
                        [
                            "Reduces the cooldown of your Mortal Strike ability by 0.8 sec and increases its damage by ",
                            change("8", "4"),
                            "%.",
                        ],
                        [
                            "Reduces the cooldown of your Mortal Strike ability by 1 sec and increases its damage by ",
                            change("10", "5"),
                            "%.",
                        ],
                    ],
                    req: "up",
                    reqDist: 1,
                },
                null,
                null,
            ],
            [
                null,
                {
                    name: "Endless Rage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_endlessrage.jpg",
                    text: formatUnchangedTalentTexts([
                        "You generate 25% more rage from damage dealt.",
                    ]),
                },
                null,
                null,
            ],
        ],
    },
    {
        name: "Fury",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/164.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_innerrage.jpg",
        talents: [
            [
                null,
                {
                    name: "Booming Voice",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_purge.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 10%.",
                        "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 20%.",
                        "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 30%.",
                        "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 40%.",
                        "Increases the area of effect and duration of your Battle Shout, Demoralizing Shout and Commanding Shout by 50%.",
                    ]),
                },
                {
                    name: "Cruelty",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_eviscerate.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to get a critical strike with melee weapons by 1%.",
                        "Increases your chance to get a critical strike with melee weapons by 2%.",
                        "Increases your chance to get a critical strike with melee weapons by 3%.",
                        "Increases your chance to get a critical strike with melee weapons by 4%.",
                        "Increases your chance to get a critical strike with melee weapons by 5%.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Improved Demoralizing Shout",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_warcry.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the melee attack power reduction of your Demoralizing Shout by 8%.",
                        "Increases the melee attack power reduction of your Demoralizing Shout by 16%.",
                        "Increases the melee attack power reduction of your Demoralizing Shout by 24%.",
                        "Increases the melee attack power reduction of your Demoralizing Shout by 32%.",
                        "Increases the melee attack power reduction of your Demoralizing Shout by 40%.",
                    ]),
                },
                {
                    name: "Unbridled Wrath",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_stoneclawtotem.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.",
                        "Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 1).",
                        "Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 2).",
                        "Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 3).",
                        "Gives you a chance to generate an additional rage point when you deal melee damage with a weapon.  Effect occurs more often than Unbridled Wrath (Rank 4).",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Cleave",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_cleave.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the bonus damage done by your Cleave ability by 40%.",
                        "Increases the bonus damage done by your Cleave ability by 80%.",
                        "Increases the bonus damage done by your Cleave ability by 120%.",
                    ]),
                },
                {
                    name: "Piercing Howl",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_deathscream.jpg",
                    text: formatUnchangedTalentTexts([
                        "Causes all enemies within 10 yards to be Dazed, reducing movement speed by 50% for 6 sec.",
                    ]),
                },
                {
                    name: "Blood Craze",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_summonimp.jpg",
                    text: [
                        [
                            "Regenerates ",
                            change("2", "1"),
                            "% of your total Health over 6 sec after being the victim of a critical strike.",
                        ],
                        [
                            "Regenerates ",
                            change("4", "2"),
                            "% of your total Health over 6 sec after being the victim of a critical strike.",
                        ],
                        [
                            "Regenerates ",
                            change("6", "3"),
                            "% of your total Health over 6 sec after being the victim of a critical strike.",
                        ],
                    ],
                },
                {
                    name: "Commanding Presence",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_focusedmind.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 5%.",
                        "Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 10%.",
                        "Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 15%.",
                        "Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 20%.",
                        "Increases the melee attack power bonus of your Battle Shout and the health bonus of your Commanding Shout by 25%.",
                    ]),
                },
            ],
            [
                {
                    name: "Dual Wield Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_dualwield.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the damage done by your offhand weapon by 5%.",
                        "Increases the damage done by your offhand weapon by 10%.",
                        "Increases the damage done by your offhand weapon by 15%.",
                        "Increases the damage done by your offhand weapon by 20%.",
                        "Increases the damage done by your offhand weapon by 25%.",
                    ]),
                },
                {
                    name: "Improved Execute",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_sword_48.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the rage cost of your Execute ability by 2.",
                        "Reduces the rage cost of your Execute ability by 5.",
                    ]),
                },
                {
                    name: "Enrage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_shadow_unholyfrenzy.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
                        "Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
                        "Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
                        "Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
                        "Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Slam",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_decisivestrike.jpg",
                    text: formatUnchangedTalentTexts([
                        "Decreases the casting time of your Slam ability by 0.5 sec.",
                        "Decreases the casting time of your Slam ability by 1 sec.",
                    ]),
                },
                {
                    name: "Sweeping Strikes",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_rogue_slicedice.jpg",
                    text: formatUnchangedTalentTexts([
                        "Your next 10 melee attacks strike an additional nearby opponent.",
                    ]),
                },
                null,
                {
                    name: "Weapon Mastery",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_weaponmastery.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the chance for your attacks to be dodged by 1% and reduces the duration of all Disarm effects used against you by 25%.  This does not stack with other Disarm duration reducing effects.",
                        "Reduces the chance for your attacks to be dodged by 2% and reduces the duration of all Disarm effects used against you by 50%.  This does not stack with other Disarm duration reducing effects.",
                    ]),
                },
            ],
            [
                {
                    name: "Improved Berserker Rage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_ancestralguardian.jpg",
                    text: [
                        [
                            "The Berserker Rage ability will generate ",
                            change("10", "5"),
                            " rage when used.",
                        ],
                        [
                            "The Berserker Rage ability will generate ",
                            change("20", "10"),
                            " rage when used.",
                        ],
                    ],
                },
                null,
                {
                    name: "Flurry",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_ghoulfrenzy.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your attack speed by 5% for your next 3 swings after dealing a melee critical strike.",
                        "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                        "Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.",
                        "Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.",
                        "Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                null,
            ],
            [
                {
                    name: "Precision",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_marksmanship.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to hit with melee weapons by 1%.",
                        "Increases your chance to hit with melee weapons by 2%.",
                        "Increases your chance to hit with melee weapons by 3%.",
                    ]),
                },
                {
                    name: "Bloodthirst",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_bloodlust.jpg",
                    text: [
                        [
                            "Instantly attack the target causing AP*0.45 damage.  In addition, the next ",
                            change("3", "5"),
                            " successful melee attacks will restore ",
                            change("1% of max health", "10 health"),
                            ".  This effect lasts 8 sec.  Damage is based on your attack power.",
                        ],
                    ],
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Improved Whirlwind",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_whirlwind.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Whirlwind ability by 1 sec.",
                        "Reduces the cooldown of your Whirlwind ability by 2 sec.",
                    ]),
                },
                null,
            ],
            [
                null,
                null,
                {
                    name: "Improved Berserker Stance",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_racial_avatar.jpg",
                    text: [
                        [
                            "Increases ",
                            change("Strength", "attack power"),
                            " by 2% and reduces threat caused by 2% while in Berserker Stance.",
                        ],
                        [
                            "Increases ",
                            change("Strength", "attack power"),
                            " by 4% and reduces threat caused by 4% while in Berserker Stance.",
                        ],
                        [
                            "Increases ",
                            change("Strength", "attack power"),
                            " by 6% and reduces threat caused by 6% while in Berserker Stance.",
                        ],
                        [
                            "Increases ",
                            change("Strength", "attack power"),
                            " by 8% and reduces threat caused by 8% while in Berserker Stance.",
                        ],
                        [
                            "Increases ",
                            change("Strength", "attack power"),
                            " by 10% and reduces threat caused by 10% while in Berserker Stance.",
                        ],
                    ],
                },
                null,
            ],
            [
                null,
                {
                    name: "Rampage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_rampage.jpg",
                    text: formatUnchangedTalentTexts([
                        "Warrior goes on a rampage, increasing attack power by 30 and causing most successful melee attacks to increase attack power by an additional 30.  This effect will stack up to 5 times.  Lasts 30 sec.  This ability can only be used after scoring a critical hit.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                null,
                null,
            ],
        ],
    },
    {
        name: "Protection",
        bg: "https://wow.zamimg.com/images/wow/talents/backgrounds/tbc/163.jpg",
        icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_shield_06.jpg",
        talents: [
            [
                {
                    name: "Improved Bloodrage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_racial_bloodrage.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the instant rage generated by your Bloodrage ability by 3.",
                        "Increases the instant rage generated by your Bloodrage ability by 6.",
                    ]),
                },
                {
                    name: "Tactical Mastery",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_enchantarmor.jpg",
                    text: formatUnchangedTalentTexts([
                        "You retain up to an additional 5 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance.",
                        "You retain up to an additional 10 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 1).",
                        "You retain up to an additional 15 of your rage points when you change stances.  Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 2).",
                    ]),
                },
                {
                    name: "Anticipation",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_mirrorimage.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your Defense skill by 4.",
                        "Increases your Defense skill by 8.",
                        "Increases your Defense skill by 12.",
                        "Increases your Defense skill by 16.",
                        "Increases your Defense skill by 20.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Shield Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_shield_06.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.",
                        "Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.",
                        "Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.",
                        "Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.",
                        "Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs.",
                    ]),
                },
                {
                    name: "Toughness",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_devotion.jpg",
                    text: [
                        [
                            "Increases your armor value from items by 2% ",
                            change("and reduces the duration of movement slowing effects by 6%"),
                            ".",
                        ],
                        [
                            "Increases your armor value from items by 4% ",
                            change("and reduces the duration of movement slowing effects by 12%"),
                            ".",
                        ],
                        [
                            "Increases your armor value from items by 6% ",
                            change("and reduces the duration of movement slowing effects by 18%"),
                            ".",
                        ],
                        [
                            "Increases your armor value from items by 8% ",
                            change("and reduces the duration of movement slowing effects by 24%"),
                            ".",
                        ],
                        [
                            "Increases your armor value from items by 10% ",
                            change("and reduces the duration of movement slowing effects by 30%"),
                            ".",
                        ],
                    ],
                },
                null,
            ],
            [
                {
                    name: "Last Stand",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_holy_ashestoashes.jpg",
                    text: formatUnchangedTalentTexts([
                        "When activated, this ability temporarily grants you 30% of your maximum health for 20 sec.  After the effect expires, the health is lost.",
                    ]),
                },
                {
                    name: "Improved Shield Block",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_defend.jpg",
                    text: formatUnchangedTalentTexts([
                        "Allows your Shield Block ability to block an additional attack and increases the duration by 1 second.",
                    ]),
                    req: "up",
                    reqDist: 1,
                },
                {
                    name: "Improved Revenge",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_revenge.jpg",
                    text: formatUnchangedTalentTexts([
                        "Gives your Revenge ability a 15% chance to stun the target for 3 sec.",
                        "Gives your Revenge ability a 30% chance to stun the target for 3 sec.",
                        "Gives your Revenge ability a 45% chance to stun the target for 3 sec.",
                    ]),
                },
                {
                    name: "Defiance",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_innerrage.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the threat generated by your attacks by 5% while in Defensive Stance and increases your expertise by 2.",
                        "Increases the threat generated by your attacks by 10% while in Defensive Stance and increases your expertise by 4.",
                        "Increases the threat generated by your attacks by 15% while in Defensive Stance and increases your expertise by 6.",
                    ]),
                },
            ],
            [
                {
                    name: "Improved Sunder Armor",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_sunder.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cost of your Sunder Armor and Devastate abilities by 1 rage point.",
                        "Reduces the cost of your Sunder Armor and Devastate abilities by 2 rage point.",
                        "Reduces the cost of your Sunder Armor and Devastate abilities by 3 rage point.",
                    ]),
                },
                {
                    name: "Improved Disarm",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_disarm.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the duration of your Disarm ability by 1 secs.",
                        "Increases the duration of your Disarm ability by 2 secs.",
                        "Increases the duration of your Disarm ability by 3 secs.",
                    ]),
                },
                {
                    name: "Improved Taunt",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/spell_nature_reincarnation.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the cooldown of your Taunt ability by 1 sec.",
                        "Reduces the cooldown of your Taunt ability by 2 sec.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Shield Wall",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_shieldwall.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the effect duration of your Shield Wall ability by 3 secs.",
                        "Increases the effect duration of your Shield Wall ability by 5 secs.",
                    ]),
                },
                {
                    name: "Concussion Blow",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_thunderbolt.jpg",
                    text: [
                        [
                            "Stuns the opponent for 5 sec.",
                            change(" and deals (0.38*AP) damage."),
                        ],
                    ],
                },
                {
                    name: "Improved Shield Bash",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_shieldbash.jpg",
                    text: [
                        [
                            "Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.,",
                            change(" and increases the damage of your Shield Slam ability by 5%."),
                        ],
                        [
                            "Gives your Shield Bash ability a 100% chance to silence the target for 3 sec.,",
                            change(" and increases the damage of your Shield Slam ability by 10%."),
                        ],
                    ],
                },
                null,
            ],
            [
                {
                    name: "Shield Mastery",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_shieldmastery.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases the amount of damage absorbed by your shield by 10%.",
                        "Increases the amount of damage absorbed by your shield by 20%.",
                        "Increases the amount of damage absorbed by your shield by 30%.",
                    ]),
                },
                null,
                {
                    name: "One-Handed Weapon Specialization",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_sword_20.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases physical damage you deal when a one-handed melee weapon is equipped by 2%.",
                        "Increases physical damage you deal when a one-handed melee weapon is equipped by 4%.",
                        "Increases physical damage you deal when a one-handed melee weapon is equipped by 6%.",
                        "Increases physical damage you deal when a one-handed melee weapon is equipped by 8%.",
                        "Increases physical damage you deal when a one-handed melee weapon is equipped by 10%.",
                    ]),
                },
                null,
            ],
            [
                {
                    name: "Improved Defensive Stance",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_defensivestance.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces all spell damage taken while in Defensive Stance by 2%.",
                        "Reduces all spell damage taken while in Defensive Stance by 4%.",
                        "Reduces all spell damage taken while in Defensive Stance by 6%.",
                    ]),
                },
                {
                    name: "Shield Slam",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_shield_05.jpg",
                    text: formatUnchangedTalentTexts([
                        "Slam the target with your shield, causing 225 to 236 damage, modified by your shield block value, and dispels 1 magic effect on the target.  Also causes a high amount of threat.",
                    ]),
                    req: "up",
                    reqDist: 2,
                },
                {
                    name: "Focused Rage",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/ability_warrior_focusedrage.jpg",
                    text: formatUnchangedTalentTexts([
                        "Reduces the rage cost of your offensive abilities by 1.",
                        "Reduces the rage cost of your offensive abilities by 2.",
                        "Reduces the rage cost of your offensive abilities by 3.",
                    ]),
                },
                null,
            ],
            [
                null,
                {
                    name: "Vitality",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_helmet_21.jpg",
                    text: formatUnchangedTalentTexts([
                        "Increases your total Stamina by 1% and your total Strength by 2%.",
                        "Increases your total Stamina by 2% and your total Strength by 4%.",
                        "Increases your total Stamina by 3% and your total Strength by 6%.",
                        "Increases your total Stamina by 4% and your total Strength by 8%.",
                        "Increases your total Stamina by 5% and your total Strength by 10%.",
                    ]),
                },
                null,
                null,
            ],
            [
                null,
                {
                    name: "Devastate",
                    icon: "https://wow.zamimg.com/images/wow/icons/medium/inv_sword_11.jpg",
                    text: formatUnchangedTalentTexts([
                        "Sunder the target's armor causing the Sunder Armor effect.  In addition, causes 50% of weapon damage plus 15 for each application of Sunder Armor on the target.  The Sunder Armor effect can stack up to 5 times.",
                    ]),
                },
                null,
                null,
            ],
        ],
    },
];
